"""Render the README benchmark leaderboard from a recorded benchmark data file.

The leaderboard table in ``README.md`` is not hand-typed: it is generated from a
real benchmark data JSON (the ``raw_runs`` records that ``compare_benchmarks``
writes) between the ``BENCHMARK_TABLE`` markers, so every cell carries an
explicit per-strategy ``n`` and a 95% confidence interval and cannot silently
drift from the underlying data. That is the whole point of this module: the
headline latency figures stop being a frozen claim and become a function of a
dataset a reader (or CI) can re-derive.

Two entry points share the same rendering path:

- ``--check`` compares the table currently in the README against a fresh render
  of the data file and exits non-zero on any drift. ``tests/test_render_readme_table.py``
  runs this so the README table is a gated artifact, not prose.
- ``--write`` re-renders the table in place. The live workflow
  (``.github/workflows/regen-readme-table.yml``) re-measures against the paid
  Gemini API and calls this to refresh the table from the new run.

Summaries are always recomputed from ``raw_runs`` (via
``compare_benchmarks.summarize_metrics``) rather than read from the file's
``summaries`` block, because older salvaged files predate the ``ci95_duration``
field. Recomputing is the single robust path that yields the CI for any file
that carries raw runs.
"""

from __future__ import annotations

import argparse
import json
import os
from collections import defaultdict

from scripts.compare_benchmarks import STRATEGIES, summarize_metrics

MARKER_START = "<!-- BENCHMARK_TABLE:START -->"
MARKER_END = "<!-- BENCHMARK_TABLE:END -->"

# Canonical dataset the README leaderboard is generated from. The live workflow
# (.github/workflows/regen-readme-table.yml) overwrites this file with a fresh
# re-measurement and re-renders the table, so the file and the README table
# always move together and `--check` stays green.
DEFAULT_DATA = os.path.join("benchmark_results", "readme_leaderboard_run.json")

_COLUMNS = [
    "Strategy",
    "n (valid/total)",
    "Avg Latency",
    "95% CI (latency)",
    "Avg Thought",
    "Max Thought",
    "Avg Cost (USD, est.)",
    "Success Rate",
    "Failure Rate",
]


def load_data(path):
    with open(path, encoding="utf-8") as handle:
        return json.load(handle)


def summaries_from_data(data):
    """Recompute per-strategy summaries from the file's raw per-run records.

    Recomputing (instead of trusting the stored ``summaries``) guarantees the
    ``ci95_duration`` field exists even for files salvaged before it was added.
    """
    runs_by_strategy = defaultdict(list)
    for run in data.get("raw_runs", []):
        runs_by_strategy[run["strategy"]].append(run)

    summaries = {}
    for strategy_key, runs in runs_by_strategy.items():
        display_name = (
            STRATEGIES[strategy_key]["name"] if strategy_key in STRATEGIES else strategy_key
        )
        summaries[strategy_key] = {"name": display_name, **summarize_metrics(runs)}
    return summaries


def _format_ci(ci95):
    if not ci95:
        return "n/a (n<2)"
    return f"[{ci95['lower']:.1f}s, {ci95['upper']:.1f}s]"


def _row(summary):
    return [
        summary["name"],
        f"{summary['successful_runs']}/{summary['total_runs']}",
        f"{summary['avg_duration']:.1f}s",
        _format_ci(summary["ci95_duration"]),
        f"{summary['avg_thought_tokens']:,.0f}",
        f"{summary['max_thought_tokens']:,.0f}",
        f"${summary['avg_cost']:.4f}",
        f"{summary['valid_output_rate'] * 100:.1f}%",
        f"{summary['failure_rate'] * 100:.1f}%",
    ]


def _sort_key(item):
    # Strategies with no valid run (avg_duration == 0) have no meaningful
    # latency, so they sort last instead of pretending to be the fastest.
    summary = item[1]
    has_valid = summary["successful_runs"] > 0
    return (0 if has_valid else 1, summary["avg_duration"] if has_valid else float("inf"))


def render_table(data):
    """Return the generated Markdown block (table + provenance caption)."""
    summaries = summaries_from_data(data)
    ordered = sorted(summaries.items(), key=_sort_key)

    lines = [
        "| " + " | ".join(_COLUMNS) + " |",
        "|" + "|".join(["---"] * len(_COLUMNS)) + "|",
    ]
    lines.extend("| " + " | ".join(_row(summary)) + " |" for _, summary in ordered)

    metadata = data.get("metadata", {})
    words = metadata.get("words", [])
    iterations = metadata.get("iterations")
    total_valid = sum(s["successful_runs"] for s in summaries.values())
    caption = (
        f"_Generated by `scripts/render_readme_table.py` from a recorded benchmark run "
        f"({len(words)} words x {iterations} iterations per strategy; {total_valid} valid runs "
        f"feed the latency stats). The 95% CI is a normal approximation over the valid-run "
        f"latencies (see `confidence_interval_95`); with this small n it is an optimistic lower "
        f"bound on uncertainty, and sub-second gaps between adjacent strategies overlap heavily "
        f"(they are within the margin, not a ranking)._"
    )

    return "\n".join(lines) + "\n\n" + caption


def replace_table(readme_text, table_block):
    if MARKER_START not in readme_text or MARKER_END not in readme_text:
        raise ValueError(
            f"README is missing the benchmark-table markers "
            f"({MARKER_START} / {MARKER_END}); cannot render in place."
        )
    prefix, rest = readme_text.split(MARKER_START, 1)
    _, suffix = rest.split(MARKER_END, 1)
    return f"{prefix}{MARKER_START}\n{table_block}\n{MARKER_END}{suffix}"


def _current_table_block(readme_text):
    if MARKER_START not in readme_text or MARKER_END not in readme_text:
        return None
    _, rest = readme_text.split(MARKER_START, 1)
    inner, _ = rest.split(MARKER_END, 1)
    return inner.strip("\n")


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--data",
        default=DEFAULT_DATA,
        help="Benchmark data JSON with raw_runs (default: the versioned leaderboard run).",
    )
    parser.add_argument("--readme", default="README.md", help="README path to render into.")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--write",
        action="store_true",
        help="Rewrite the table between the markers in place.",
    )
    mode.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the README table is not in sync with --data.",
    )
    args = parser.parse_args(argv)

    data = load_data(args.data)
    table_block = render_table(data)

    with open(args.readme, encoding="utf-8") as handle:
        readme_text = handle.read()

    if args.check:
        current = _current_table_block(readme_text)
        if current is None:
            print(f"README {args.readme} is missing the benchmark-table markers.")
            return 1
        if current != table_block.strip("\n"):
            print(
                "README benchmark table is OUT OF SYNC with "
                f"{args.data}. Run: python -m scripts.render_readme_table --write"
            )
            return 1
        print("README benchmark table is in sync with the data.")
        return 0

    updated = replace_table(readme_text, table_block)
    if args.write:
        if updated != readme_text:
            with open(args.readme, "w", encoding="utf-8") as handle:
                handle.write(updated)
            print(f"Rewrote benchmark table in {args.readme}.")
        else:
            print(f"{args.readme} benchmark table already up to date.")
        return 0

    # No mode flag: print the rendered block to stdout (dry run).
    print(table_block)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
